### ISSUE TITLE
Cave generation broken?

### ISSUE THREAD

**Issue by Pseudonomenclature** [b3spectacled/modernbetaforge#3]
A lot of caves seem to be randomly cut off by big flat walls of stone. And looking at it in spectator mode it seems like there are multiple caves being cut off along the same line like this.

Most obvious with the circular cave rooms which are sometimes just cut in half.

Maybe it's happening along chunk borders?

**Comment by b3spectacled** [comment]
I believe this is expected behavior. It's a cave generation bug that was fixed in Beta 1.8. If you find instances of it occurring where it shouldn't compared to the original MC version, please provide seeds/coords/etc.
