### ISSUE TITLE
Port to something newer than 1.12.2

### ISSUE THREAD

**Issue by roryyamm** [b3spectacled/modernbetaforge#4]
While it's nice this exists on Forge at all, and can be enjoyed with all the various Forge-only mods that were around back then and will never leave for Fabric, there's no getting around the fact that 1.12.2 is about six years old at this point. That's about as much time between us and 1.12 as there was between 1.12 and Beta 1.7.3. At this point, it's only useful for anarchy servers and those most stubborn (or abandoned) mods. 

The fabric version can support 1.19, 1.18, and 1.17. Why can't the Forge version?

**Comment by b3spectacled** [comment]
This was a one-off project for a friend who specifically set up a 1.12.2 server. I'm not looking to do more beyond this.

**Comment by roryyamm** [comment]
Fair enough.
