### ISSUE TITLE
Allow for release biomes

### ISSUE THREAD

**Issue by Pokeman2003** [b3spectacled/modernbetaforge#6]
Clarification: I meant adding the release biome generation to the biomes slider. I was really, REALLY tired when I wrote this.

I really love this mod, but it somewhat bothers me that I can't have the release biomes in the alpha terrain like I wanted, but I CAN have beta terrain. Do you mind adding release biomes to the slider too?

I'd also like a custom biome list option if that's possible, because there are mods that introduce new biomes, with probably the most egregious example being Biomes o' Plenty with its own separate generation option in 1.12.2. It's okay if this isn't an consideration though, especially considering the existing options of setting things.

**Comment by b3spectacled** [comment]
The single biome slider option already allows you to change the biome to any single vanilla/mod biomes when you're using the Single biome source option. When you use the classic Alpha preset, the default is the Alpha biome but you can of course change this.

EDIT: If I misunderstood and you meant having a vanilla-style biome generator, then right now that is not on the cards.

**Comment by Pokeman2003** [comment]
It was the latter. It feels weird that it's not in the list, considering you do allow release terrain generation. Oh well, I guess this can be reopened later.

**Comment by b3spectacled** [comment]
Reopening this because I have implemented just this in a beta release. I did try implementing this a long time ago, but ran into technical issues. Put a set of fresh eyes on this this time around and managed to get something working.

Feel free to test this and offer feedback. You can try it out here:

https://github.com/b3spectacled/modernbetaforge/releases/tag/1.12.2-1.2.2.0-beta.1

**Comment by b3spectacled** [comment]
Closing now that I have an implementation I am happy with in 1.12.2-1.2.2.0. Please enjoy!
